module TW exposing
    ( bg_auto
    , bg_black
    , bg_blue_100
    , bg_blue_200
    , bg_blue_300
    , bg_blue_400
    , bg_blue_500
    , bg_blue_600
    , bg_blue_700
    , bg_blue_800
    , bg_blue_900
    , bg_bottom
    , bg_center
    , bg_contain
    , bg_cover
    , bg_current
    , bg_fixed
    , bg_gray_100
    , bg_gray_200
    , bg_gray_300
    , bg_gray_400
    , bg_gray_500
    , bg_gray_600
    , bg_gray_700
    , bg_gray_800
    , bg_gray_900
    , bg_green_100
    , bg_green_200
    , bg_green_300
    , bg_green_400
    , bg_green_500
    , bg_green_600
    , bg_green_700
    , bg_green_800
    , bg_green_900
    , bg_indigo_100
    , bg_indigo_200
    , bg_indigo_300
    , bg_indigo_400
    , bg_indigo_500
    , bg_indigo_600
    , bg_indigo_700
    , bg_indigo_800
    , bg_indigo_900
    , bg_left
    , bg_left_bottom
    , bg_left_top
    , bg_local
    , bg_no_repeat
    , bg_orange_100
    , bg_orange_200
    , bg_orange_300
    , bg_orange_400
    , bg_orange_500
    , bg_orange_600
    , bg_orange_700
    , bg_orange_800
    , bg_orange_900
    , bg_pink_100
    , bg_pink_200
    , bg_pink_300
    , bg_pink_400
    , bg_pink_500
    , bg_pink_600
    , bg_pink_700
    , bg_pink_800
    , bg_pink_900
    , bg_purple_100
    , bg_purple_200
    , bg_purple_300
    , bg_purple_400
    , bg_purple_500
    , bg_purple_600
    , bg_purple_700
    , bg_purple_800
    , bg_purple_900
    , bg_red_100
    , bg_red_200
    , bg_red_300
    , bg_red_400
    , bg_red_500
    , bg_red_600
    , bg_red_700
    , bg_red_800
    , bg_red_900
    , bg_repeat
    , bg_repeat_round
    , bg_repeat_space
    , bg_repeat_x
    , bg_repeat_y
    , bg_right
    , bg_right_bottom
    , bg_right_top
    , bg_scroll
    , bg_teal_100
    , bg_teal_200
    , bg_teal_300
    , bg_teal_400
    , bg_teal_500
    , bg_teal_600
    , bg_teal_700
    , bg_teal_800
    , bg_teal_900
    , bg_top
    , bg_transparent
    , bg_white
    , bg_yellow_100
    , bg_yellow_200
    , bg_yellow_300
    , bg_yellow_400
    , bg_yellow_500
    , bg_yellow_600
    , bg_yellow_700
    , bg_yellow_800
    , bg_yellow_900
    , hover__bg_black
    , hover__bg_blue_100
    , hover__bg_blue_200
    , hover__bg_blue_300
    , hover__bg_blue_400
    , hover__bg_blue_500
    , hover__bg_blue_600
    , hover__bg_blue_700
    , hover__bg_blue_800
    , hover__bg_blue_900
    , hover__bg_current
    , hover__bg_gray_100
    , hover__bg_gray_200
    , hover__bg_gray_300
    , hover__bg_gray_400
    , hover__bg_gray_500
    , hover__bg_gray_600
    , hover__bg_gray_700
    , hover__bg_gray_800
    , hover__bg_gray_900
    , hover__bg_green_100
    , hover__bg_green_200
    , hover__bg_green_300
    , hover__bg_green_400
    , hover__bg_green_500
    , hover__bg_green_600
    , hover__bg_green_700
    , hover__bg_green_800
    , hover__bg_green_900
    , hover__bg_indigo_100
    , hover__bg_indigo_200
    , hover__bg_indigo_300
    , hover__bg_indigo_400
    , hover__bg_indigo_500
    , hover__bg_indigo_600
    , hover__bg_indigo_700
    , hover__bg_indigo_800
    , hover__bg_indigo_900
    , hover__bg_orange_100
    , hover__bg_orange_200
    , hover__bg_orange_300
    , hover__bg_orange_400
    , hover__bg_orange_500
    , hover__bg_orange_600
    , hover__bg_orange_700
    , hover__bg_orange_800
    , hover__bg_orange_900
    , hover__bg_pink_100
    , hover__bg_pink_200
    , hover__bg_pink_300
    , hover__bg_pink_400
    , hover__bg_pink_500
    , hover__bg_pink_600
    , hover__bg_pink_700
    , hover__bg_pink_800
    , hover__bg_pink_900
    , hover__bg_purple_100
    , hover__bg_purple_200
    , hover__bg_purple_300
    , hover__bg_purple_400
    , hover__bg_purple_500
    , hover__bg_purple_600
    , hover__bg_purple_700
    , hover__bg_purple_800
    , hover__bg_purple_900
    , hover__bg_red_100
    , hover__bg_red_200
    , hover__bg_red_300
    , hover__bg_red_400
    , hover__bg_red_500
    , hover__bg_red_600
    , hover__bg_red_700
    , hover__bg_red_800
    , hover__bg_red_900
    , hover__bg_teal_100
    , hover__bg_teal_200
    , hover__bg_teal_300
    , hover__bg_teal_400
    , hover__bg_teal_500
    , hover__bg_teal_600
    , hover__bg_teal_700
    , hover__bg_teal_800
    , hover__bg_teal_900
    , hover__bg_transparent
    , hover__bg_white
    , hover__bg_yellow_100
    , hover__bg_yellow_200
    , hover__bg_yellow_300
    , hover__bg_yellow_400
    , hover__bg_yellow_500
    , hover__bg_yellow_600
    , hover__bg_yellow_700
    , hover__bg_yellow_800
    , hover__bg_yellow_900
    , hover__border_black
    , hover__border_blue_100
    , hover__border_blue_200
    , hover__border_blue_300
    , hover__border_blue_400
    , hover__border_blue_500
    , hover__border_blue_600
    , hover__border_blue_700
    , hover__border_blue_800
    , hover__border_blue_900
    , hover__border_current
    , hover__border_gray_100
    , hover__border_gray_200
    , hover__border_gray_300
    , hover__border_gray_400
    , hover__border_gray_500
    , hover__border_gray_600
    , hover__border_gray_700
    , hover__border_gray_800
    , hover__border_gray_900
    , hover__border_green_100
    , hover__border_green_200
    , hover__border_green_300
    , hover__border_green_400
    , hover__border_green_500
    , hover__border_green_600
    , hover__border_green_700
    , hover__border_green_800
    , hover__border_green_900
    , hover__border_indigo_100
    , hover__border_indigo_200
    , hover__border_indigo_300
    , hover__border_indigo_400
    , hover__border_indigo_500
    , hover__border_indigo_600
    , hover__border_indigo_700
    , hover__border_indigo_800
    , hover__border_indigo_900
    , hover__border_orange_100
    , hover__border_orange_200
    , hover__border_orange_300
    , hover__border_orange_400
    , hover__border_orange_500
    , hover__border_orange_600
    , hover__border_orange_700
    , hover__border_orange_800
    , hover__border_orange_900
    , hover__border_pink_100
    , hover__border_pink_200
    , hover__border_pink_300
    , hover__border_pink_400
    , hover__border_pink_500
    , hover__border_pink_600
    , hover__border_pink_700
    , hover__border_pink_800
    , hover__border_pink_900
    , hover__border_purple_100
    , hover__border_purple_200
    , hover__border_purple_300
    , hover__border_purple_400
    , hover__border_purple_500
    , hover__border_purple_600
    , hover__border_purple_700
    , hover__border_purple_800
    , hover__border_purple_900
    , hover__border_red_100
    , hover__border_red_200
    , hover__border_red_300
    , hover__border_red_400
    , hover__border_red_500
    , hover__border_red_600
    , hover__border_red_700
    , hover__border_red_800
    , hover__border_red_900
    , hover__border_teal_100
    , hover__border_teal_200
    , hover__border_teal_300
    , hover__border_teal_400
    , hover__border_teal_500
    , hover__border_teal_600
    , hover__border_teal_700
    , hover__border_teal_800
    , hover__border_teal_900
    , hover__border_transparent
    , hover__border_white
    , hover__border_yellow_100
    , hover__border_yellow_200
    , hover__border_yellow_300
    , hover__border_yellow_400
    , hover__border_yellow_500
    , hover__border_yellow_600
    , hover__border_yellow_700
    , hover__border_yellow_800
    , hover__border_yellow_900
    , hover__font_black
    , hover__font_bold
    , hover__font_extrabold
    , hover__font_hairline
    , hover__font_light
    , hover__font_medium
    , hover__font_normal
    , hover__font_semibold
    , hover__font_thin
    , hover__line_through
    , hover__no_underline
    , hover__opacity_0
    , hover__opacity_100
    , hover__opacity_25
    , hover__opacity_50
    , hover__opacity_75
    , hover__shadow
    , hover__shadow_2xl
    , hover__shadow_inner
    , hover__shadow_lg
    , hover__shadow_md
    , hover__shadow_none
    , hover__shadow_outline
    , hover__shadow_sm
    , hover__shadow_xl
    , hover__shadow_xs
    , hover__text_black
    , hover__text_blue_100
    , hover__text_blue_200
    , hover__text_blue_300
    , hover__text_blue_400
    , hover__text_blue_500
    , hover__text_blue_600
    , hover__text_blue_700
    , hover__text_blue_800
    , hover__text_blue_900
    , hover__text_current
    , hover__text_gray_100
    , hover__text_gray_200
    , hover__text_gray_300
    , hover__text_gray_400
    , hover__text_gray_500
    , hover__text_gray_600
    , hover__text_gray_700
    , hover__text_gray_800
    , hover__text_gray_900
    , hover__text_green_100
    , hover__text_green_200
    , hover__text_green_300
    , hover__text_green_400
    , hover__text_green_500
    , hover__text_green_600
    , hover__text_green_700
    , hover__text_green_800
    , hover__text_green_900
    , hover__text_indigo_100
    , hover__text_indigo_200
    , hover__text_indigo_300
    , hover__text_indigo_400
    , hover__text_indigo_500
    , hover__text_indigo_600
    , hover__text_indigo_700
    , hover__text_indigo_800
    , hover__text_indigo_900
    , hover__text_orange_100
    , hover__text_orange_200
    , hover__text_orange_300
    , hover__text_orange_400
    , hover__text_orange_500
    , hover__text_orange_600
    , hover__text_orange_700
    , hover__text_orange_800
    , hover__text_orange_900
    , hover__text_pink_100
    , hover__text_pink_200
    , hover__text_pink_300
    , hover__text_pink_400
    , hover__text_pink_500
    , hover__text_pink_600
    , hover__text_pink_700
    , hover__text_pink_800
    , hover__text_pink_900
    , hover__text_purple_100
    , hover__text_purple_200
    , hover__text_purple_300
    , hover__text_purple_400
    , hover__text_purple_500
    , hover__text_purple_600
    , hover__text_purple_700
    , hover__text_purple_800
    , hover__text_purple_900
    , hover__text_red_100
    , hover__text_red_200
    , hover__text_red_300
    , hover__text_red_400
    , hover__text_red_500
    , hover__text_red_600
    , hover__text_red_700
    , hover__text_red_800
    , hover__text_red_900
    , hover__text_teal_100
    , hover__text_teal_200
    , hover__text_teal_300
    , hover__text_teal_400
    , hover__text_teal_500
    , hover__text_teal_600
    , hover__text_teal_700
    , hover__text_teal_800
    , hover__text_teal_900
    , hover__text_transparent
    , hover__text_white
    , hover__text_yellow_100
    , hover__text_yellow_200
    , hover__text_yellow_300
    , hover__text_yellow_400
    , hover__text_yellow_500
    , hover__text_yellow_600
    , hover__text_yellow_700
    , hover__text_yellow_800
    , hover__text_yellow_900
    , hover__underline
    , lg__absolute
    , lg__align_baseline
    , lg__align_bottom
    , lg__align_middle
    , lg__align_text_bottom
    , lg__align_text_top
    , lg__align_top
    , lg__antialiased
    , lg__appearance_none
    , lg__bg_auto
    , lg__bg_black
    , lg__bg_blue_100
    , lg__bg_blue_200
    , lg__bg_blue_300
    , lg__bg_blue_400
    , lg__bg_blue_500
    , lg__bg_blue_600
    , lg__bg_blue_700
    , lg__bg_blue_800
    , lg__bg_blue_900
    , lg__bg_bottom
    , lg__bg_center
    , lg__bg_contain
    , lg__bg_cover
    , lg__bg_current
    , lg__bg_fixed
    , lg__bg_gray_100
    , lg__bg_gray_200
    , lg__bg_gray_300
    , lg__bg_gray_400
    , lg__bg_gray_500
    , lg__bg_gray_600
    , lg__bg_gray_700
    , lg__bg_gray_800
    , lg__bg_gray_900
    , lg__bg_green_100
    , lg__bg_green_200
    , lg__bg_green_300
    , lg__bg_green_400
    , lg__bg_green_500
    , lg__bg_green_600
    , lg__bg_green_700
    , lg__bg_green_800
    , lg__bg_green_900
    , lg__bg_indigo_100
    , lg__bg_indigo_200
    , lg__bg_indigo_300
    , lg__bg_indigo_400
    , lg__bg_indigo_500
    , lg__bg_indigo_600
    , lg__bg_indigo_700
    , lg__bg_indigo_800
    , lg__bg_indigo_900
    , lg__bg_left
    , lg__bg_left_bottom
    , lg__bg_left_top
    , lg__bg_local
    , lg__bg_no_repeat
    , lg__bg_orange_100
    , lg__bg_orange_200
    , lg__bg_orange_300
    , lg__bg_orange_400
    , lg__bg_orange_500
    , lg__bg_orange_600
    , lg__bg_orange_700
    , lg__bg_orange_800
    , lg__bg_orange_900
    , lg__bg_pink_100
    , lg__bg_pink_200
    , lg__bg_pink_300
    , lg__bg_pink_400
    , lg__bg_pink_500
    , lg__bg_pink_600
    , lg__bg_pink_700
    , lg__bg_pink_800
    , lg__bg_pink_900
    , lg__bg_purple_100
    , lg__bg_purple_200
    , lg__bg_purple_300
    , lg__bg_purple_400
    , lg__bg_purple_500
    , lg__bg_purple_600
    , lg__bg_purple_700
    , lg__bg_purple_800
    , lg__bg_purple_900
    , lg__bg_red_100
    , lg__bg_red_200
    , lg__bg_red_300
    , lg__bg_red_400
    , lg__bg_red_500
    , lg__bg_red_600
    , lg__bg_red_700
    , lg__bg_red_800
    , lg__bg_red_900
    , lg__bg_repeat
    , lg__bg_repeat_round
    , lg__bg_repeat_space
    , lg__bg_repeat_x
    , lg__bg_repeat_y
    , lg__bg_right
    , lg__bg_right_bottom
    , lg__bg_right_top
    , lg__bg_scroll
    , lg__bg_teal_100
    , lg__bg_teal_200
    , lg__bg_teal_300
    , lg__bg_teal_400
    , lg__bg_teal_500
    , lg__bg_teal_600
    , lg__bg_teal_700
    , lg__bg_teal_800
    , lg__bg_teal_900
    , lg__bg_top
    , lg__bg_transparent
    , lg__bg_white
    , lg__bg_yellow_100
    , lg__bg_yellow_200
    , lg__bg_yellow_300
    , lg__bg_yellow_400
    , lg__bg_yellow_500
    , lg__bg_yellow_600
    , lg__bg_yellow_700
    , lg__bg_yellow_800
    , lg__bg_yellow_900
    , lg__block
    , lg__border
    , lg__border_0
    , lg__border_2
    , lg__border_4
    , lg__border_8
    , lg__border_b
    , lg__border_b_0
    , lg__border_b_2
    , lg__border_b_4
    , lg__border_b_8
    , lg__border_black
    , lg__border_blue_100
    , lg__border_blue_200
    , lg__border_blue_300
    , lg__border_blue_400
    , lg__border_blue_500
    , lg__border_blue_600
    , lg__border_blue_700
    , lg__border_blue_800
    , lg__border_blue_900
    , lg__border_collapse
    , lg__border_current
    , lg__border_dashed
    , lg__border_dotted
    , lg__border_double
    , lg__border_gray_100
    , lg__border_gray_200
    , lg__border_gray_300
    , lg__border_gray_400
    , lg__border_gray_500
    , lg__border_gray_600
    , lg__border_gray_700
    , lg__border_gray_800
    , lg__border_gray_900
    , lg__border_green_100
    , lg__border_green_200
    , lg__border_green_300
    , lg__border_green_400
    , lg__border_green_500
    , lg__border_green_600
    , lg__border_green_700
    , lg__border_green_800
    , lg__border_green_900
    , lg__border_indigo_100
    , lg__border_indigo_200
    , lg__border_indigo_300
    , lg__border_indigo_400
    , lg__border_indigo_500
    , lg__border_indigo_600
    , lg__border_indigo_700
    , lg__border_indigo_800
    , lg__border_indigo_900
    , lg__border_l
    , lg__border_l_0
    , lg__border_l_2
    , lg__border_l_4
    , lg__border_l_8
    , lg__border_none
    , lg__border_orange_100
    , lg__border_orange_200
    , lg__border_orange_300
    , lg__border_orange_400
    , lg__border_orange_500
    , lg__border_orange_600
    , lg__border_orange_700
    , lg__border_orange_800
    , lg__border_orange_900
    , lg__border_pink_100
    , lg__border_pink_200
    , lg__border_pink_300
    , lg__border_pink_400
    , lg__border_pink_500
    , lg__border_pink_600
    , lg__border_pink_700
    , lg__border_pink_800
    , lg__border_pink_900
    , lg__border_purple_100
    , lg__border_purple_200
    , lg__border_purple_300
    , lg__border_purple_400
    , lg__border_purple_500
    , lg__border_purple_600
    , lg__border_purple_700
    , lg__border_purple_800
    , lg__border_purple_900
    , lg__border_r
    , lg__border_r_0
    , lg__border_r_2
    , lg__border_r_4
    , lg__border_r_8
    , lg__border_red_100
    , lg__border_red_200
    , lg__border_red_300
    , lg__border_red_400
    , lg__border_red_500
    , lg__border_red_600
    , lg__border_red_700
    , lg__border_red_800
    , lg__border_red_900
    , lg__border_separate
    , lg__border_solid
    , lg__border_t
    , lg__border_t_0
    , lg__border_t_2
    , lg__border_t_4
    , lg__border_t_8
    , lg__border_teal_100
    , lg__border_teal_200
    , lg__border_teal_300
    , lg__border_teal_400
    , lg__border_teal_500
    , lg__border_teal_600
    , lg__border_teal_700
    , lg__border_teal_800
    , lg__border_teal_900
    , lg__border_transparent
    , lg__border_white
    , lg__border_yellow_100
    , lg__border_yellow_200
    , lg__border_yellow_300
    , lg__border_yellow_400
    , lg__border_yellow_500
    , lg__border_yellow_600
    , lg__border_yellow_700
    , lg__border_yellow_800
    , lg__border_yellow_900
    , lg__bottom_0
    , lg__bottom_auto
    , lg__box_border
    , lg__box_content
    , lg__break_all
    , lg__break_normal
    , lg__break_words
    , lg__capitalize
    , lg__clear_both
    , lg__clear_left
    , lg__clear_none
    , lg__clear_right
    , lg__clearfix
    , lg__col_auto
    , lg__col_end_1
    , lg__col_end_10
    , lg__col_end_11
    , lg__col_end_12
    , lg__col_end_13
    , lg__col_end_2
    , lg__col_end_3
    , lg__col_end_4
    , lg__col_end_5
    , lg__col_end_6
    , lg__col_end_7
    , lg__col_end_8
    , lg__col_end_9
    , lg__col_end_auto
    , lg__col_gap_0
    , lg__col_gap_1
    , lg__col_gap_10
    , lg__col_gap_12
    , lg__col_gap_16
    , lg__col_gap_2
    , lg__col_gap_20
    , lg__col_gap_24
    , lg__col_gap_3
    , lg__col_gap_32
    , lg__col_gap_4
    , lg__col_gap_40
    , lg__col_gap_48
    , lg__col_gap_5
    , lg__col_gap_56
    , lg__col_gap_6
    , lg__col_gap_64
    , lg__col_gap_8
    , lg__col_gap_px
    , lg__col_span_1
    , lg__col_span_10
    , lg__col_span_11
    , lg__col_span_12
    , lg__col_span_2
    , lg__col_span_3
    , lg__col_span_4
    , lg__col_span_5
    , lg__col_span_6
    , lg__col_span_7
    , lg__col_span_8
    , lg__col_span_9
    , lg__col_start_1
    , lg__col_start_10
    , lg__col_start_11
    , lg__col_start_12
    , lg__col_start_13
    , lg__col_start_2
    , lg__col_start_3
    , lg__col_start_4
    , lg__col_start_5
    , lg__col_start_6
    , lg__col_start_7
    , lg__col_start_8
    , lg__col_start_9
    , lg__col_start_auto
    , lg__container
    , lg__content_around
    , lg__content_between
    , lg__content_center
    , lg__content_end
    , lg__content_start
    , lg__cursor_auto
    , lg__cursor_default
    , lg__cursor_move
    , lg__cursor_not_allowed
    , lg__cursor_pointer
    , lg__cursor_text
    , lg__cursor_wait
    , lg__delay_100
    , lg__delay_1000
    , lg__delay_150
    , lg__delay_200
    , lg__delay_300
    , lg__delay_500
    , lg__delay_700
    , lg__delay_75
    , lg__divide_black
    , lg__divide_blue_100
    , lg__divide_blue_200
    , lg__divide_blue_300
    , lg__divide_blue_400
    , lg__divide_blue_500
    , lg__divide_blue_600
    , lg__divide_blue_700
    , lg__divide_blue_800
    , lg__divide_blue_900
    , lg__divide_current
    , lg__divide_gray_100
    , lg__divide_gray_200
    , lg__divide_gray_300
    , lg__divide_gray_400
    , lg__divide_gray_500
    , lg__divide_gray_600
    , lg__divide_gray_700
    , lg__divide_gray_800
    , lg__divide_gray_900
    , lg__divide_green_100
    , lg__divide_green_200
    , lg__divide_green_300
    , lg__divide_green_400
    , lg__divide_green_500
    , lg__divide_green_600
    , lg__divide_green_700
    , lg__divide_green_800
    , lg__divide_green_900
    , lg__divide_indigo_100
    , lg__divide_indigo_200
    , lg__divide_indigo_300
    , lg__divide_indigo_400
    , lg__divide_indigo_500
    , lg__divide_indigo_600
    , lg__divide_indigo_700
    , lg__divide_indigo_800
    , lg__divide_indigo_900
    , lg__divide_orange_100
    , lg__divide_orange_200
    , lg__divide_orange_300
    , lg__divide_orange_400
    , lg__divide_orange_500
    , lg__divide_orange_600
    , lg__divide_orange_700
    , lg__divide_orange_800
    , lg__divide_orange_900
    , lg__divide_pink_100
    , lg__divide_pink_200
    , lg__divide_pink_300
    , lg__divide_pink_400
    , lg__divide_pink_500
    , lg__divide_pink_600
    , lg__divide_pink_700
    , lg__divide_pink_800
    , lg__divide_pink_900
    , lg__divide_purple_100
    , lg__divide_purple_200
    , lg__divide_purple_300
    , lg__divide_purple_400
    , lg__divide_purple_500
    , lg__divide_purple_600
    , lg__divide_purple_700
    , lg__divide_purple_800
    , lg__divide_purple_900
    , lg__divide_red_100
    , lg__divide_red_200
    , lg__divide_red_300
    , lg__divide_red_400
    , lg__divide_red_500
    , lg__divide_red_600
    , lg__divide_red_700
    , lg__divide_red_800
    , lg__divide_red_900
    , lg__divide_teal_100
    , lg__divide_teal_200
    , lg__divide_teal_300
    , lg__divide_teal_400
    , lg__divide_teal_500
    , lg__divide_teal_600
    , lg__divide_teal_700
    , lg__divide_teal_800
    , lg__divide_teal_900
    , lg__divide_transparent
    , lg__divide_white
    , lg__divide_yellow_100
    , lg__divide_yellow_200
    , lg__divide_yellow_300
    , lg__divide_yellow_400
    , lg__divide_yellow_500
    , lg__divide_yellow_600
    , lg__divide_yellow_700
    , lg__divide_yellow_800
    , lg__divide_yellow_900
    , lg__duration_100
    , lg__duration_1000
    , lg__duration_150
    , lg__duration_200
    , lg__duration_300
    , lg__duration_500
    , lg__duration_700
    , lg__duration_75
    , lg__ease_in
    , lg__ease_in_out
    , lg__ease_linear
    , lg__ease_out
    , lg__fill_current
    , lg__fixed
    , lg__flex
    , lg__flex_1
    , lg__flex_auto
    , lg__flex_col
    , lg__flex_col_reverse
    , lg__flex_grow
    , lg__flex_grow_0
    , lg__flex_initial
    , lg__flex_no_wrap
    , lg__flex_none
    , lg__flex_row
    , lg__flex_row_reverse
    , lg__flex_shrink
    , lg__flex_shrink_0
    , lg__flex_wrap
    , lg__flex_wrap_reverse
    , lg__float_left
    , lg__float_none
    , lg__float_right
    , lg__flow_root
    , lg__focus__bg_black
    , lg__focus__bg_blue_100
    , lg__focus__bg_blue_200
    , lg__focus__bg_blue_300
    , lg__focus__bg_blue_400
    , lg__focus__bg_blue_500
    , lg__focus__bg_blue_600
    , lg__focus__bg_blue_700
    , lg__focus__bg_blue_800
    , lg__focus__bg_blue_900
    , lg__focus__bg_current
    , lg__focus__bg_gray_100
    , lg__focus__bg_gray_200
    , lg__focus__bg_gray_300
    , lg__focus__bg_gray_400
    , lg__focus__bg_gray_500
    , lg__focus__bg_gray_600
    , lg__focus__bg_gray_700
    , lg__focus__bg_gray_800
    , lg__focus__bg_gray_900
    , lg__focus__bg_green_100
    , lg__focus__bg_green_200
    , lg__focus__bg_green_300
    , lg__focus__bg_green_400
    , lg__focus__bg_green_500
    , lg__focus__bg_green_600
    , lg__focus__bg_green_700
    , lg__focus__bg_green_800
    , lg__focus__bg_green_900
    , lg__focus__bg_indigo_100
    , lg__focus__bg_indigo_200
    , lg__focus__bg_indigo_300
    , lg__focus__bg_indigo_400
    , lg__focus__bg_indigo_500
    , lg__focus__bg_indigo_600
    , lg__focus__bg_indigo_700
    , lg__focus__bg_indigo_800
    , lg__focus__bg_indigo_900
    , lg__focus__bg_orange_100
    , lg__focus__bg_orange_200
    , lg__focus__bg_orange_300
    , lg__focus__bg_orange_400
    , lg__focus__bg_orange_500
    , lg__focus__bg_orange_600
    , lg__focus__bg_orange_700
    , lg__focus__bg_orange_800
    , lg__focus__bg_orange_900
    , lg__focus__bg_pink_100
    , lg__focus__bg_pink_200
    , lg__focus__bg_pink_300
    , lg__focus__bg_pink_400
    , lg__focus__bg_pink_500
    , lg__focus__bg_pink_600
    , lg__focus__bg_pink_700
    , lg__focus__bg_pink_800
    , lg__focus__bg_pink_900
    , lg__focus__bg_purple_100
    , lg__focus__bg_purple_200
    , lg__focus__bg_purple_300
    , lg__focus__bg_purple_400
    , lg__focus__bg_purple_500
    , lg__focus__bg_purple_600
    , lg__focus__bg_purple_700
    , lg__focus__bg_purple_800
    , lg__focus__bg_purple_900
    , lg__focus__bg_red_100
    , lg__focus__bg_red_200
    , lg__focus__bg_red_300
    , lg__focus__bg_red_400
    , lg__focus__bg_red_500
    , lg__focus__bg_red_600
    , lg__focus__bg_red_700
    , lg__focus__bg_red_800
    , lg__focus__bg_red_900
    , lg__focus__bg_teal_100
    , lg__focus__bg_teal_200
    , lg__focus__bg_teal_300
    , lg__focus__bg_teal_400
    , lg__focus__bg_teal_500
    , lg__focus__bg_teal_600
    , lg__focus__bg_teal_700
    , lg__focus__bg_teal_800
    , lg__focus__bg_teal_900
    , lg__focus__bg_transparent
    , lg__focus__bg_white
    , lg__focus__bg_yellow_100
    , lg__focus__bg_yellow_200
    , lg__focus__bg_yellow_300
    , lg__focus__bg_yellow_400
    , lg__focus__bg_yellow_500
    , lg__focus__bg_yellow_600
    , lg__focus__bg_yellow_700
    , lg__focus__bg_yellow_800
    , lg__focus__bg_yellow_900
    , lg__focus__border_black
    , lg__focus__border_blue_100
    , lg__focus__border_blue_200
    , lg__focus__border_blue_300
    , lg__focus__border_blue_400
    , lg__focus__border_blue_500
    , lg__focus__border_blue_600
    , lg__focus__border_blue_700
    , lg__focus__border_blue_800
    , lg__focus__border_blue_900
    , lg__focus__border_current
    , lg__focus__border_gray_100
    , lg__focus__border_gray_200
    , lg__focus__border_gray_300
    , lg__focus__border_gray_400
    , lg__focus__border_gray_500
    , lg__focus__border_gray_600
    , lg__focus__border_gray_700
    , lg__focus__border_gray_800
    , lg__focus__border_gray_900
    , lg__focus__border_green_100
    , lg__focus__border_green_200
    , lg__focus__border_green_300
    , lg__focus__border_green_400
    , lg__focus__border_green_500
    , lg__focus__border_green_600
    , lg__focus__border_green_700
    , lg__focus__border_green_800
    , lg__focus__border_green_900
    , lg__focus__border_indigo_100
    , lg__focus__border_indigo_200
    , lg__focus__border_indigo_300
    , lg__focus__border_indigo_400
    , lg__focus__border_indigo_500
    , lg__focus__border_indigo_600
    , lg__focus__border_indigo_700
    , lg__focus__border_indigo_800
    , lg__focus__border_indigo_900
    , lg__focus__border_orange_100
    , lg__focus__border_orange_200
    , lg__focus__border_orange_300
    , lg__focus__border_orange_400
    , lg__focus__border_orange_500
    , lg__focus__border_orange_600
    , lg__focus__border_orange_700
    , lg__focus__border_orange_800
    , lg__focus__border_orange_900
    , lg__focus__border_pink_100
    , lg__focus__border_pink_200
    , lg__focus__border_pink_300
    , lg__focus__border_pink_400
    , lg__focus__border_pink_500
    , lg__focus__border_pink_600
    , lg__focus__border_pink_700
    , lg__focus__border_pink_800
    , lg__focus__border_pink_900
    , lg__focus__border_purple_100
    , lg__focus__border_purple_200
    , lg__focus__border_purple_300
    , lg__focus__border_purple_400
    , lg__focus__border_purple_500
    , lg__focus__border_purple_600
    , lg__focus__border_purple_700
    , lg__focus__border_purple_800
    , lg__focus__border_purple_900
    , lg__focus__border_red_100
    , lg__focus__border_red_200
    , lg__focus__border_red_300
    , lg__focus__border_red_400
    , lg__focus__border_red_500
    , lg__focus__border_red_600
    , lg__focus__border_red_700
    , lg__focus__border_red_800
    , lg__focus__border_red_900
    , lg__focus__border_teal_100
    , lg__focus__border_teal_200
    , lg__focus__border_teal_300
    , lg__focus__border_teal_400
    , lg__focus__border_teal_500
    , lg__focus__border_teal_600
    , lg__focus__border_teal_700
    , lg__focus__border_teal_800
    , lg__focus__border_teal_900
    , lg__focus__border_transparent
    , lg__focus__border_white
    , lg__focus__border_yellow_100
    , lg__focus__border_yellow_200
    , lg__focus__border_yellow_300
    , lg__focus__border_yellow_400
    , lg__focus__border_yellow_500
    , lg__focus__border_yellow_600
    , lg__focus__border_yellow_700
    , lg__focus__border_yellow_800
    , lg__focus__border_yellow_900
    , lg__focus__font_black
    , lg__focus__font_bold
    , lg__focus__font_extrabold
    , lg__focus__font_hairline
    , lg__focus__font_light
    , lg__focus__font_medium
    , lg__focus__font_normal
    , lg__focus__font_semibold
    , lg__focus__font_thin
    , lg__focus__line_through
    , lg__focus__no_underline
    , lg__focus__not_sr_only
    , lg__focus__opacity_0
    , lg__focus__opacity_100
    , lg__focus__opacity_25
    , lg__focus__opacity_50
    , lg__focus__opacity_75
    , lg__focus__outline_none
    , lg__focus__placeholder_black
    , lg__focus__placeholder_blue_100
    , lg__focus__placeholder_blue_200
    , lg__focus__placeholder_blue_300
    , lg__focus__placeholder_blue_400
    , lg__focus__placeholder_blue_500
    , lg__focus__placeholder_blue_600
    , lg__focus__placeholder_blue_700
    , lg__focus__placeholder_blue_800
    , lg__focus__placeholder_blue_900
    , lg__focus__placeholder_current
    , lg__focus__placeholder_gray_100
    , lg__focus__placeholder_gray_200
    , lg__focus__placeholder_gray_300
    , lg__focus__placeholder_gray_400
    , lg__focus__placeholder_gray_500
    , lg__focus__placeholder_gray_600
    , lg__focus__placeholder_gray_700
    , lg__focus__placeholder_gray_800
    , lg__focus__placeholder_gray_900
    , lg__focus__placeholder_green_100
    , lg__focus__placeholder_green_200
    , lg__focus__placeholder_green_300
    , lg__focus__placeholder_green_400
    , lg__focus__placeholder_green_500
    , lg__focus__placeholder_green_600
    , lg__focus__placeholder_green_700
    , lg__focus__placeholder_green_800
    , lg__focus__placeholder_green_900
    , lg__focus__placeholder_indigo_100
    , lg__focus__placeholder_indigo_200
    , lg__focus__placeholder_indigo_300
    , lg__focus__placeholder_indigo_400
    , lg__focus__placeholder_indigo_500
    , lg__focus__placeholder_indigo_600
    , lg__focus__placeholder_indigo_700
    , lg__focus__placeholder_indigo_800
    , lg__focus__placeholder_indigo_900
    , lg__focus__placeholder_orange_100
    , lg__focus__placeholder_orange_200
    , lg__focus__placeholder_orange_300
    , lg__focus__placeholder_orange_400
    , lg__focus__placeholder_orange_500
    , lg__focus__placeholder_orange_600
    , lg__focus__placeholder_orange_700
    , lg__focus__placeholder_orange_800
    , lg__focus__placeholder_orange_900
    , lg__focus__placeholder_pink_100
    , lg__focus__placeholder_pink_200
    , lg__focus__placeholder_pink_300
    , lg__focus__placeholder_pink_400
    , lg__focus__placeholder_pink_500
    , lg__focus__placeholder_pink_600
    , lg__focus__placeholder_pink_700
    , lg__focus__placeholder_pink_800
    , lg__focus__placeholder_pink_900
    , lg__focus__placeholder_purple_100
    , lg__focus__placeholder_purple_200
    , lg__focus__placeholder_purple_300
    , lg__focus__placeholder_purple_400
    , lg__focus__placeholder_purple_500
    , lg__focus__placeholder_purple_600
    , lg__focus__placeholder_purple_700
    , lg__focus__placeholder_purple_800
    , lg__focus__placeholder_purple_900
    , lg__focus__placeholder_red_100
    , lg__focus__placeholder_red_200
    , lg__focus__placeholder_red_300
    , lg__focus__placeholder_red_400
    , lg__focus__placeholder_red_500
    , lg__focus__placeholder_red_600
    , lg__focus__placeholder_red_700
    , lg__focus__placeholder_red_800
    , lg__focus__placeholder_red_900
    , lg__focus__placeholder_teal_100
    , lg__focus__placeholder_teal_200
    , lg__focus__placeholder_teal_300
    , lg__focus__placeholder_teal_400
    , lg__focus__placeholder_teal_500
    , lg__focus__placeholder_teal_600
    , lg__focus__placeholder_teal_700
    , lg__focus__placeholder_teal_800
    , lg__focus__placeholder_teal_900
    , lg__focus__placeholder_transparent
    , lg__focus__placeholder_white
    , lg__focus__placeholder_yellow_100
    , lg__focus__placeholder_yellow_200
    , lg__focus__placeholder_yellow_300
    , lg__focus__placeholder_yellow_400
    , lg__focus__placeholder_yellow_500
    , lg__focus__placeholder_yellow_600
    , lg__focus__placeholder_yellow_700
    , lg__focus__placeholder_yellow_800
    , lg__focus__placeholder_yellow_900
    , lg__focus__shadow
    , lg__focus__shadow_2xl
    , lg__focus__shadow_inner
    , lg__focus__shadow_lg
    , lg__focus__shadow_md
    , lg__focus__shadow_none
    , lg__focus__shadow_outline
    , lg__focus__shadow_sm
    , lg__focus__shadow_xl
    , lg__focus__shadow_xs
    , lg__focus__sr_only
    , lg__focus__text_black
    , lg__focus__text_blue_100
    , lg__focus__text_blue_200
    , lg__focus__text_blue_300
    , lg__focus__text_blue_400
    , lg__focus__text_blue_500
    , lg__focus__text_blue_600
    , lg__focus__text_blue_700
    , lg__focus__text_blue_800
    , lg__focus__text_blue_900
    , lg__focus__text_current
    , lg__focus__text_gray_100
    , lg__focus__text_gray_200
    , lg__focus__text_gray_300
    , lg__focus__text_gray_400
    , lg__focus__text_gray_500
    , lg__focus__text_gray_600
    , lg__focus__text_gray_700
    , lg__focus__text_gray_800
    , lg__focus__text_gray_900
    , lg__focus__text_green_100
    , lg__focus__text_green_200
    , lg__focus__text_green_300
    , lg__focus__text_green_400
    , lg__focus__text_green_500
    , lg__focus__text_green_600
    , lg__focus__text_green_700
    , lg__focus__text_green_800
    , lg__focus__text_green_900
    , lg__focus__text_indigo_100
    , lg__focus__text_indigo_200
    , lg__focus__text_indigo_300
    , lg__focus__text_indigo_400
    , lg__focus__text_indigo_500
    , lg__focus__text_indigo_600
    , lg__focus__text_indigo_700
    , lg__focus__text_indigo_800
    , lg__focus__text_indigo_900
    , lg__focus__text_orange_100
    , lg__focus__text_orange_200
    , lg__focus__text_orange_300
    , lg__focus__text_orange_400
    , lg__focus__text_orange_500
    , lg__focus__text_orange_600
    , lg__focus__text_orange_700
    , lg__focus__text_orange_800
    , lg__focus__text_orange_900
    , lg__focus__text_pink_100
    , lg__focus__text_pink_200
    , lg__focus__text_pink_300
    , lg__focus__text_pink_400
    , lg__focus__text_pink_500
    , lg__focus__text_pink_600
    , lg__focus__text_pink_700
    , lg__focus__text_pink_800
    , lg__focus__text_pink_900
    , lg__focus__text_purple_100
    , lg__focus__text_purple_200
    , lg__focus__text_purple_300
    , lg__focus__text_purple_400
    , lg__focus__text_purple_500
    , lg__focus__text_purple_600
    , lg__focus__text_purple_700
    , lg__focus__text_purple_800
    , lg__focus__text_purple_900
    , lg__focus__text_red_100
    , lg__focus__text_red_200
    , lg__focus__text_red_300
    , lg__focus__text_red_400
    , lg__focus__text_red_500
    , lg__focus__text_red_600
    , lg__focus__text_red_700
    , lg__focus__text_red_800
    , lg__focus__text_red_900
    , lg__focus__text_teal_100
    , lg__focus__text_teal_200
    , lg__focus__text_teal_300
    , lg__focus__text_teal_400
    , lg__focus__text_teal_500
    , lg__focus__text_teal_600
    , lg__focus__text_teal_700
    , lg__focus__text_teal_800
    , lg__focus__text_teal_900
    , lg__focus__text_transparent
    , lg__focus__text_white
    , lg__focus__text_yellow_100
    , lg__focus__text_yellow_200
    , lg__focus__text_yellow_300
    , lg__focus__text_yellow_400
    , lg__focus__text_yellow_500
    , lg__focus__text_yellow_600
    , lg__focus__text_yellow_700
    , lg__focus__text_yellow_800
    , lg__focus__text_yellow_900
    , lg__focus__underline
    , lg__font_black
    , lg__font_bold
    , lg__font_extrabold
    , lg__font_hairline
    , lg__font_light
    , lg__font_medium
    , lg__font_mono
    , lg__font_normal
    , lg__font_sans
    , lg__font_semibold
    , lg__font_serif
    , lg__font_thin
    , lg__gap_0
    , lg__gap_1
    , lg__gap_10
    , lg__gap_12
    , lg__gap_16
    , lg__gap_2
    , lg__gap_20
    , lg__gap_24
    , lg__gap_3
    , lg__gap_32
    , lg__gap_4
    , lg__gap_40
    , lg__gap_48
    , lg__gap_5
    , lg__gap_56
    , lg__gap_6
    , lg__gap_64
    , lg__gap_8
    , lg__gap_px
    , lg__grid
    , lg__grid_cols_1
    , lg__grid_cols_10
    , lg__grid_cols_11
    , lg__grid_cols_12
    , lg__grid_cols_2
    , lg__grid_cols_3
    , lg__grid_cols_4
    , lg__grid_cols_5
    , lg__grid_cols_6
    , lg__grid_cols_7
    , lg__grid_cols_8
    , lg__grid_cols_9
    , lg__grid_cols_none
    , lg__grid_flow_col
    , lg__grid_flow_col_dense
    , lg__grid_flow_row
    , lg__grid_flow_row_dense
    , lg__grid_rows_1
    , lg__grid_rows_2
    , lg__grid_rows_3
    , lg__grid_rows_4
    , lg__grid_rows_5
    , lg__grid_rows_6
    , lg__grid_rows_none
    , lg__h_0
    , lg__h_1
    , lg__h_10
    , lg__h_12
    , lg__h_16
    , lg__h_2
    , lg__h_20
    , lg__h_24
    , lg__h_3
    , lg__h_32
    , lg__h_4
    , lg__h_40
    , lg__h_48
    , lg__h_5
    , lg__h_56
    , lg__h_6
    , lg__h_64
    , lg__h_8
    , lg__h_auto
    , lg__h_full
    , lg__h_px
    , lg__h_screen
    , lg__hidden
    , lg__hover__bg_black
    , lg__hover__bg_blue_100
    , lg__hover__bg_blue_200
    , lg__hover__bg_blue_300
    , lg__hover__bg_blue_400
    , lg__hover__bg_blue_500
    , lg__hover__bg_blue_600
    , lg__hover__bg_blue_700
    , lg__hover__bg_blue_800
    , lg__hover__bg_blue_900
    , lg__hover__bg_current
    , lg__hover__bg_gray_100
    , lg__hover__bg_gray_200
    , lg__hover__bg_gray_300
    , lg__hover__bg_gray_400
    , lg__hover__bg_gray_500
    , lg__hover__bg_gray_600
    , lg__hover__bg_gray_700
    , lg__hover__bg_gray_800
    , lg__hover__bg_gray_900
    , lg__hover__bg_green_100
    , lg__hover__bg_green_200
    , lg__hover__bg_green_300
    , lg__hover__bg_green_400
    , lg__hover__bg_green_500
    , lg__hover__bg_green_600
    , lg__hover__bg_green_700
    , lg__hover__bg_green_800
    , lg__hover__bg_green_900
    , lg__hover__bg_indigo_100
    , lg__hover__bg_indigo_200
    , lg__hover__bg_indigo_300
    , lg__hover__bg_indigo_400
    , lg__hover__bg_indigo_500
    , lg__hover__bg_indigo_600
    , lg__hover__bg_indigo_700
    , lg__hover__bg_indigo_800
    , lg__hover__bg_indigo_900
    , lg__hover__bg_orange_100
    , lg__hover__bg_orange_200
    , lg__hover__bg_orange_300
    , lg__hover__bg_orange_400
    , lg__hover__bg_orange_500
    , lg__hover__bg_orange_600
    , lg__hover__bg_orange_700
    , lg__hover__bg_orange_800
    , lg__hover__bg_orange_900
    , lg__hover__bg_pink_100
    , lg__hover__bg_pink_200
    , lg__hover__bg_pink_300
    , lg__hover__bg_pink_400
    , lg__hover__bg_pink_500
    , lg__hover__bg_pink_600
    , lg__hover__bg_pink_700
    , lg__hover__bg_pink_800
    , lg__hover__bg_pink_900
    , lg__hover__bg_purple_100
    , lg__hover__bg_purple_200
    , lg__hover__bg_purple_300
    , lg__hover__bg_purple_400
    , lg__hover__bg_purple_500
    , lg__hover__bg_purple_600
    , lg__hover__bg_purple_700
    , lg__hover__bg_purple_800
    , lg__hover__bg_purple_900
    , lg__hover__bg_red_100
    , lg__hover__bg_red_200
    , lg__hover__bg_red_300
    , lg__hover__bg_red_400
    , lg__hover__bg_red_500
    , lg__hover__bg_red_600
    , lg__hover__bg_red_700
    , lg__hover__bg_red_800
    , lg__hover__bg_red_900
    , lg__hover__bg_teal_100
    , lg__hover__bg_teal_200
    , lg__hover__bg_teal_300
    , lg__hover__bg_teal_400
    , lg__hover__bg_teal_500
    , lg__hover__bg_teal_600
    , lg__hover__bg_teal_700
    , lg__hover__bg_teal_800
    , lg__hover__bg_teal_900
    , lg__hover__bg_transparent
    , lg__hover__bg_white
    , lg__hover__bg_yellow_100
    , lg__hover__bg_yellow_200
    , lg__hover__bg_yellow_300
    , lg__hover__bg_yellow_400
    , lg__hover__bg_yellow_500
    , lg__hover__bg_yellow_600
    , lg__hover__bg_yellow_700
    , lg__hover__bg_yellow_800
    , lg__hover__bg_yellow_900
    , lg__hover__border_black
    , lg__hover__border_blue_100
    , lg__hover__border_blue_200
    , lg__hover__border_blue_300
    , lg__hover__border_blue_400
    , lg__hover__border_blue_500
    , lg__hover__border_blue_600
    , lg__hover__border_blue_700
    , lg__hover__border_blue_800
    , lg__hover__border_blue_900
    , lg__hover__border_current
    , lg__hover__border_gray_100
    , lg__hover__border_gray_200
    , lg__hover__border_gray_300
    , lg__hover__border_gray_400
    , lg__hover__border_gray_500
    , lg__hover__border_gray_600
    , lg__hover__border_gray_700
    , lg__hover__border_gray_800
    , lg__hover__border_gray_900
    , lg__hover__border_green_100
    , lg__hover__border_green_200
    , lg__hover__border_green_300
    , lg__hover__border_green_400
    , lg__hover__border_green_500
    , lg__hover__border_green_600
    , lg__hover__border_green_700
    , lg__hover__border_green_800
    , lg__hover__border_green_900
    , lg__hover__border_indigo_100
    , lg__hover__border_indigo_200
    , lg__hover__border_indigo_300
    , lg__hover__border_indigo_400
    , lg__hover__border_indigo_500
    , lg__hover__border_indigo_600
    , lg__hover__border_indigo_700
    , lg__hover__border_indigo_800
    , lg__hover__border_indigo_900
    , lg__hover__border_orange_100
    , lg__hover__border_orange_200
    , lg__hover__border_orange_300
    , lg__hover__border_orange_400
    , lg__hover__border_orange_500
    , lg__hover__border_orange_600
    , lg__hover__border_orange_700
    , lg__hover__border_orange_800
    , lg__hover__border_orange_900
    , lg__hover__border_pink_100
    , lg__hover__border_pink_200
    , lg__hover__border_pink_300
    , lg__hover__border_pink_400
    , lg__hover__border_pink_500
    , lg__hover__border_pink_600
    , lg__hover__border_pink_700
    , lg__hover__border_pink_800
    , lg__hover__border_pink_900
    , lg__hover__border_purple_100
    , lg__hover__border_purple_200
    , lg__hover__border_purple_300
    , lg__hover__border_purple_400
    , lg__hover__border_purple_500
    , lg__hover__border_purple_600
    , lg__hover__border_purple_700
    , lg__hover__border_purple_800
    , lg__hover__border_purple_900
    , lg__hover__border_red_100
    , lg__hover__border_red_200
    , lg__hover__border_red_300
    , lg__hover__border_red_400
    , lg__hover__border_red_500
    , lg__hover__border_red_600
    , lg__hover__border_red_700
    , lg__hover__border_red_800
    , lg__hover__border_red_900
    , lg__hover__border_teal_100
    , lg__hover__border_teal_200
    , lg__hover__border_teal_300
    , lg__hover__border_teal_400
    , lg__hover__border_teal_500
    , lg__hover__border_teal_600
    , lg__hover__border_teal_700
    , lg__hover__border_teal_800
    , lg__hover__border_teal_900
    , lg__hover__border_transparent
    , lg__hover__border_white
    , lg__hover__border_yellow_100
    , lg__hover__border_yellow_200
    , lg__hover__border_yellow_300
    , lg__hover__border_yellow_400
    , lg__hover__border_yellow_500
    , lg__hover__border_yellow_600
    , lg__hover__border_yellow_700
    , lg__hover__border_yellow_800
    , lg__hover__border_yellow_900
    , lg__hover__font_black
    , lg__hover__font_bold
    , lg__hover__font_extrabold
    , lg__hover__font_hairline
    , lg__hover__font_light
    , lg__hover__font_medium
    , lg__hover__font_normal
    , lg__hover__font_semibold
    , lg__hover__font_thin
    , lg__hover__line_through
    , lg__hover__no_underline
    , lg__hover__opacity_0
    , lg__hover__opacity_100
    , lg__hover__opacity_25
    , lg__hover__opacity_50
    , lg__hover__opacity_75
    , lg__hover__shadow
    , lg__hover__shadow_2xl
    , lg__hover__shadow_inner
    , lg__hover__shadow_lg
    , lg__hover__shadow_md
    , lg__hover__shadow_none
    , lg__hover__shadow_outline
    , lg__hover__shadow_sm
    , lg__hover__shadow_xl
    , lg__hover__shadow_xs
    , lg__hover__text_black
    , lg__hover__text_blue_100
    , lg__hover__text_blue_200
    , lg__hover__text_blue_300
    , lg__hover__text_blue_400
    , lg__hover__text_blue_500
    , lg__hover__text_blue_600
    , lg__hover__text_blue_700
    , lg__hover__text_blue_800
    , lg__hover__text_blue_900
    , lg__hover__text_current
    , lg__hover__text_gray_100
    , lg__hover__text_gray_200
    , lg__hover__text_gray_300
    , lg__hover__text_gray_400
    , lg__hover__text_gray_500
    , lg__hover__text_gray_600
    , lg__hover__text_gray_700
    , lg__hover__text_gray_800
    , lg__hover__text_gray_900
    , lg__hover__text_green_100
    , lg__hover__text_green_200
    , lg__hover__text_green_300
    , lg__hover__text_green_400
    , lg__hover__text_green_500
    , lg__hover__text_green_600
    , lg__hover__text_green_700
    , lg__hover__text_green_800
    , lg__hover__text_green_900
    , lg__hover__text_indigo_100
    , lg__hover__text_indigo_200
    , lg__hover__text_indigo_300
    , lg__hover__text_indigo_400
    , lg__hover__text_indigo_500
    , lg__hover__text_indigo_600
    , lg__hover__text_indigo_700
    , lg__hover__text_indigo_800
    , lg__hover__text_indigo_900
    , lg__hover__text_orange_100
    , lg__hover__text_orange_200
    , lg__hover__text_orange_300
    , lg__hover__text_orange_400
    , lg__hover__text_orange_500
    , lg__hover__text_orange_600
    , lg__hover__text_orange_700
    , lg__hover__text_orange_800
    , lg__hover__text_orange_900
    , lg__hover__text_pink_100
    , lg__hover__text_pink_200
    , lg__hover__text_pink_300
    , lg__hover__text_pink_400
    , lg__hover__text_pink_500
    , lg__hover__text_pink_600
    , lg__hover__text_pink_700
    , lg__hover__text_pink_800
    , lg__hover__text_pink_900
    , lg__hover__text_purple_100
    , lg__hover__text_purple_200
    , lg__hover__text_purple_300
    , lg__hover__text_purple_400
    , lg__hover__text_purple_500
    , lg__hover__text_purple_600
    , lg__hover__text_purple_700
    , lg__hover__text_purple_800
    , lg__hover__text_purple_900
    , lg__hover__text_red_100
    , lg__hover__text_red_200
    , lg__hover__text_red_300
    , lg__hover__text_red_400
    , lg__hover__text_red_500
    , lg__hover__text_red_600
    , lg__hover__text_red_700
    , lg__hover__text_red_800
    , lg__hover__text_red_900
    , lg__hover__text_teal_100
    , lg__hover__text_teal_200
    , lg__hover__text_teal_300
    , lg__hover__text_teal_400
    , lg__hover__text_teal_500
    , lg__hover__text_teal_600
    , lg__hover__text_teal_700
    , lg__hover__text_teal_800
    , lg__hover__text_teal_900
    , lg__hover__text_transparent
    , lg__hover__text_white
    , lg__hover__text_yellow_100
    , lg__hover__text_yellow_200
    , lg__hover__text_yellow_300
    , lg__hover__text_yellow_400
    , lg__hover__text_yellow_500
    , lg__hover__text_yellow_600
    , lg__hover__text_yellow_700
    , lg__hover__text_yellow_800
    , lg__hover__text_yellow_900
    , lg__hover__underline
    , lg__inline
    , lg__inline_block
    , lg__inline_flex
    , lg__inline_grid
    , lg__inset_0
    , lg__inset_auto
    , lg__inset_x_0
    , lg__inset_x_auto
    , lg__inset_y_0
    , lg__inset_y_auto
    , lg__invisible
    , lg__italic
    , lg__items_baseline
    , lg__items_center
    , lg__items_end
    , lg__items_start
    , lg__items_stretch
    , lg__justify_around
    , lg__justify_between
    , lg__justify_center
    , lg__justify_end
    , lg__justify_evenly
    , lg__justify_start
    , lg__leading_10
    , lg__leading_3
    , lg__leading_4
    , lg__leading_5
    , lg__leading_6
    , lg__leading_7
    , lg__leading_8
    , lg__leading_9
    , lg__leading_loose
    , lg__leading_none
    , lg__leading_normal
    , lg__leading_relaxed
    , lg__leading_snug
    , lg__leading_tight
    , lg__left_0
    , lg__left_auto
    , lg__line_through
    , lg__list_decimal
    , lg__list_disc
    , lg__list_inside
    , lg__list_none
    , lg__list_outside
    , lg__lowercase
    , lg__m_0
    , lg__m_1
    , lg__m_10
    , lg__m_12
    , lg__m_16
    , lg__m_2
    , lg__m_20
    , lg__m_24
    , lg__m_3
    , lg__m_32
    , lg__m_4
    , lg__m_40
    , lg__m_48
    , lg__m_5
    , lg__m_56
    , lg__m_6
    , lg__m_64
    , lg__m_8
    , lg__m_auto
    , lg__m_px
    , lg__max_h_full
    , lg__max_h_screen
    , lg__max_w_2xl
    , lg__max_w_3xl
    , lg__max_w_4xl
    , lg__max_w_5xl
    , lg__max_w_6xl
    , lg__max_w_full
    , lg__max_w_lg
    , lg__max_w_md
    , lg__max_w_none
    , lg__max_w_screen_lg
    , lg__max_w_screen_md
    , lg__max_w_screen_sm
    , lg__max_w_screen_xl
    , lg__max_w_sm
    , lg__max_w_xl
    , lg__max_w_xs
    , lg__mb_0
    , lg__mb_1
    , lg__mb_10
    , lg__mb_12
    , lg__mb_16
    , lg__mb_2
    , lg__mb_20
    , lg__mb_24
    , lg__mb_3
    , lg__mb_32
    , lg__mb_4
    , lg__mb_40
    , lg__mb_48
    , lg__mb_5
    , lg__mb_56
    , lg__mb_6
    , lg__mb_64
    , lg__mb_8
    , lg__mb_auto
    , lg__mb_px
    , lg__min_h_0
    , lg__min_h_full
    , lg__min_h_screen
    , lg__min_w_0
    , lg__min_w_full
    , lg__ml_0
    , lg__ml_1
    , lg__ml_10
    , lg__ml_12
    , lg__ml_16
    , lg__ml_2
    , lg__ml_20
    , lg__ml_24
    , lg__ml_3
    , lg__ml_32
    , lg__ml_4
    , lg__ml_40
    , lg__ml_48
    , lg__ml_5
    , lg__ml_56
    , lg__ml_6
    , lg__ml_64
    , lg__ml_8
    , lg__ml_auto
    , lg__ml_px
    , lg__mr_0
    , lg__mr_1
    , lg__mr_10
    , lg__mr_12
    , lg__mr_16
    , lg__mr_2
    , lg__mr_20
    , lg__mr_24
    , lg__mr_3
    , lg__mr_32
    , lg__mr_4
    , lg__mr_40
    , lg__mr_48
    , lg__mr_5
    , lg__mr_56
    , lg__mr_6
    , lg__mr_64
    , lg__mr_8
    , lg__mr_auto
    , lg__mr_px
    , lg__mt_0
    , lg__mt_1
    , lg__mt_10
    , lg__mt_12
    , lg__mt_16
    , lg__mt_2
    , lg__mt_20
    , lg__mt_24
    , lg__mt_3
    , lg__mt_32
    , lg__mt_4
    , lg__mt_40
    , lg__mt_48
    , lg__mt_5
    , lg__mt_56
    , lg__mt_6
    , lg__mt_64
    , lg__mt_8
    , lg__mt_auto
    , lg__mt_px
    , lg__mx_0
    , lg__mx_1
    , lg__mx_10
    , lg__mx_12
    , lg__mx_16
    , lg__mx_2
    , lg__mx_20
    , lg__mx_24
    , lg__mx_3
    , lg__mx_32
    , lg__mx_4
    , lg__mx_40
    , lg__mx_48
    , lg__mx_5
    , lg__mx_56
    , lg__mx_6
    , lg__mx_64
    , lg__mx_8
    , lg__mx_auto
    , lg__mx_px
    , lg__my_0
    , lg__my_1
    , lg__my_10
    , lg__my_12
    , lg__my_16
    , lg__my_2
    , lg__my_20
    , lg__my_24
    , lg__my_3
    , lg__my_32
    , lg__my_4
    , lg__my_40
    , lg__my_48
    , lg__my_5
    , lg__my_56
    , lg__my_6
    , lg__my_64
    , lg__my_8
    , lg__my_auto
    , lg__my_px
    , lg__neg_m_1
    , lg__neg_m_10
    , lg__neg_m_12
    , lg__neg_m_16
    , lg__neg_m_2
    , lg__neg_m_20
    , lg__neg_m_24
    , lg__neg_m_3
    , lg__neg_m_32
    , lg__neg_m_4
    , lg__neg_m_40
    , lg__neg_m_48
    , lg__neg_m_5
    , lg__neg_m_56
    , lg__neg_m_6
    , lg__neg_m_64
    , lg__neg_m_8
    , lg__neg_m_px
    , lg__neg_mb_1
    , lg__neg_mb_10
    , lg__neg_mb_12
    , lg__neg_mb_16
    , lg__neg_mb_2
    , lg__neg_mb_20
    , lg__neg_mb_24
    , lg__neg_mb_3
    , lg__neg_mb_32
    , lg__neg_mb_4
    , lg__neg_mb_40
    , lg__neg_mb_48
    , lg__neg_mb_5
    , lg__neg_mb_56
    , lg__neg_mb_6
    , lg__neg_mb_64
    , lg__neg_mb_8
    , lg__neg_mb_px
    , lg__neg_ml_1
    , lg__neg_ml_10
    , lg__neg_ml_12
    , lg__neg_ml_16
    , lg__neg_ml_2
    , lg__neg_ml_20
    , lg__neg_ml_24
    , lg__neg_ml_3
    , lg__neg_ml_32
    , lg__neg_ml_4
    , lg__neg_ml_40
    , lg__neg_ml_48
    , lg__neg_ml_5
    , lg__neg_ml_56
    , lg__neg_ml_6
    , lg__neg_ml_64
    , lg__neg_ml_8
    , lg__neg_ml_px
    , lg__neg_mr_1
    , lg__neg_mr_10
    , lg__neg_mr_12
    , lg__neg_mr_16
    , lg__neg_mr_2
    , lg__neg_mr_20
    , lg__neg_mr_24
    , lg__neg_mr_3
    , lg__neg_mr_32
    , lg__neg_mr_4
    , lg__neg_mr_40
    , lg__neg_mr_48
    , lg__neg_mr_5
    , lg__neg_mr_56
    , lg__neg_mr_6
    , lg__neg_mr_64
    , lg__neg_mr_8
    , lg__neg_mr_px
    , lg__neg_mt_1
    , lg__neg_mt_10
    , lg__neg_mt_12
    , lg__neg_mt_16
    , lg__neg_mt_2
    , lg__neg_mt_20
    , lg__neg_mt_24
    , lg__neg_mt_3
    , lg__neg_mt_32
    , lg__neg_mt_4
    , lg__neg_mt_40
    , lg__neg_mt_48
    , lg__neg_mt_5
    , lg__neg_mt_56
    , lg__neg_mt_6
    , lg__neg_mt_64
    , lg__neg_mt_8
    , lg__neg_mt_px
    , lg__neg_mx_1
    , lg__neg_mx_10
    , lg__neg_mx_12
    , lg__neg_mx_16
    , lg__neg_mx_2
    , lg__neg_mx_20
    , lg__neg_mx_24
    , lg__neg_mx_3
    , lg__neg_mx_32
    , lg__neg_mx_4
    , lg__neg_mx_40
    , lg__neg_mx_48
    , lg__neg_mx_5
    , lg__neg_mx_56
    , lg__neg_mx_6
    , lg__neg_mx_64
    , lg__neg_mx_8
    , lg__neg_mx_px
    , lg__neg_my_1
    , lg__neg_my_10
    , lg__neg_my_12
    , lg__neg_my_16
    , lg__neg_my_2
    , lg__neg_my_20
    , lg__neg_my_24
    , lg__neg_my_3
    , lg__neg_my_32
    , lg__neg_my_4
    , lg__neg_my_40
    , lg__neg_my_48
    , lg__neg_my_5
    , lg__neg_my_56
    , lg__neg_my_6
    , lg__neg_my_64
    , lg__neg_my_8
    , lg__neg_my_px
    , lg__no_underline
    , lg__normal_case
    , lg__not_italic
    , lg__not_sr_only
    , lg__object_bottom
    , lg__object_center
    , lg__object_contain
    , lg__object_cover
    , lg__object_fill
    , lg__object_left
    , lg__object_left_bottom
    , lg__object_left_top
    , lg__object_none
    , lg__object_right
    , lg__object_right_bottom
    , lg__object_right_top
    , lg__object_scale_down
    , lg__object_top
    , lg__opacity_0
    , lg__opacity_100
    , lg__opacity_25
    , lg__opacity_50
    , lg__opacity_75
    , lg__order_1
    , lg__order_10
    , lg__order_11
    , lg__order_12
    , lg__order_2
    , lg__order_3
    , lg__order_4
    , lg__order_5
    , lg__order_6
    , lg__order_7
    , lg__order_8
    , lg__order_9
    , lg__order_first
    , lg__order_last
    , lg__order_none
    , lg__origin_bottom
    , lg__origin_bottom_left
    , lg__origin_bottom_right
    , lg__origin_center
    , lg__origin_left
    , lg__origin_right
    , lg__origin_top
    , lg__origin_top_left
    , lg__origin_top_right
    , lg__outline_none
    , lg__overflow_auto
    , lg__overflow_hidden
    , lg__overflow_scroll
    , lg__overflow_visible
    , lg__overflow_x_auto
    , lg__overflow_x_hidden
    , lg__overflow_x_scroll
    , lg__overflow_x_visible
    , lg__overflow_y_auto
    , lg__overflow_y_hidden
    , lg__overflow_y_scroll
    , lg__overflow_y_visible
    , lg__p_0
    , lg__p_1
    , lg__p_10
    , lg__p_12
    , lg__p_16
    , lg__p_2
    , lg__p_20
    , lg__p_24
    , lg__p_3
    , lg__p_32
    , lg__p_4
    , lg__p_40
    , lg__p_48
    , lg__p_5
    , lg__p_56
    , lg__p_6
    , lg__p_64
    , lg__p_8
    , lg__p_px
    , lg__pb_0
    , lg__pb_1
    , lg__pb_10
    , lg__pb_12
    , lg__pb_16
    , lg__pb_2
    , lg__pb_20
    , lg__pb_24
    , lg__pb_3
    , lg__pb_32
    , lg__pb_4
    , lg__pb_40
    , lg__pb_48
    , lg__pb_5
    , lg__pb_56
    , lg__pb_6
    , lg__pb_64
    , lg__pb_8
    , lg__pb_px
    , lg__pl_0
    , lg__pl_1
    , lg__pl_10
    , lg__pl_12
    , lg__pl_16
    , lg__pl_2
    , lg__pl_20
    , lg__pl_24
    , lg__pl_3
    , lg__pl_32
    , lg__pl_4
    , lg__pl_40
    , lg__pl_48
    , lg__pl_5
    , lg__pl_56
    , lg__pl_6
    , lg__pl_64
    , lg__pl_8
    , lg__pl_px
    , lg__placeholder_black
    , lg__placeholder_blue_100
    , lg__placeholder_blue_200
    , lg__placeholder_blue_300
    , lg__placeholder_blue_400
    , lg__placeholder_blue_500
    , lg__placeholder_blue_600
    , lg__placeholder_blue_700
    , lg__placeholder_blue_800
    , lg__placeholder_blue_900
    , lg__placeholder_current
    , lg__placeholder_gray_100
    , lg__placeholder_gray_200
    , lg__placeholder_gray_300
    , lg__placeholder_gray_400
    , lg__placeholder_gray_500
    , lg__placeholder_gray_600
    , lg__placeholder_gray_700
    , lg__placeholder_gray_800
    , lg__placeholder_gray_900
    , lg__placeholder_green_100
    , lg__placeholder_green_200
    , lg__placeholder_green_300
    , lg__placeholder_green_400
    , lg__placeholder_green_500
    , lg__placeholder_green_600
    , lg__placeholder_green_700
    , lg__placeholder_green_800
    , lg__placeholder_green_900
    , lg__placeholder_indigo_100
    , lg__placeholder_indigo_200
    , lg__placeholder_indigo_300
    , lg__placeholder_indigo_400
    , lg__placeholder_indigo_500
    , lg__placeholder_indigo_600
    , lg__placeholder_indigo_700
    , lg__placeholder_indigo_800
    , lg__placeholder_indigo_900
    , lg__placeholder_orange_100
    , lg__placeholder_orange_200
    , lg__placeholder_orange_300
    , lg__placeholder_orange_400
    , lg__placeholder_orange_500
    , lg__placeholder_orange_600
    , lg__placeholder_orange_700
    , lg__placeholder_orange_800
    , lg__placeholder_orange_900
    , lg__placeholder_pink_100
    , lg__placeholder_pink_200
    , lg__placeholder_pink_300
    , lg__placeholder_pink_400
    , lg__placeholder_pink_500
    , lg__placeholder_pink_600
    , lg__placeholder_pink_700
    , lg__placeholder_pink_800
    , lg__placeholder_pink_900
    , lg__placeholder_purple_100
    , lg__placeholder_purple_200
    , lg__placeholder_purple_300
    , lg__placeholder_purple_400
    , lg__placeholder_purple_500
    , lg__placeholder_purple_600
    , lg__placeholder_purple_700
    , lg__placeholder_purple_800
    , lg__placeholder_purple_900
    , lg__placeholder_red_100
    , lg__placeholder_red_200
    , lg__placeholder_red_300
    , lg__placeholder_red_400
    , lg__placeholder_red_500
    , lg__placeholder_red_600
    , lg__placeholder_red_700
    , lg__placeholder_red_800
    , lg__placeholder_red_900
    , lg__placeholder_teal_100
    , lg__placeholder_teal_200
    , lg__placeholder_teal_300
    , lg__placeholder_teal_400
    , lg__placeholder_teal_500
    , lg__placeholder_teal_600
    , lg__placeholder_teal_700
    , lg__placeholder_teal_800
    , lg__placeholder_teal_900
    , lg__placeholder_transparent
    , lg__placeholder_white
    , lg__placeholder_yellow_100
    , lg__placeholder_yellow_200
    , lg__placeholder_yellow_300
    , lg__placeholder_yellow_400
    , lg__placeholder_yellow_500
    , lg__placeholder_yellow_600
    , lg__placeholder_yellow_700
    , lg__placeholder_yellow_800
    , lg__placeholder_yellow_900
    , lg__pointer_events_auto
    , lg__pointer_events_none
    , lg__pr_0
    , lg__pr_1
    , lg__pr_10
    , lg__pr_12
    , lg__pr_16
    , lg__pr_2
    , lg__pr_20
    , lg__pr_24
    , lg__pr_3
    , lg__pr_32
    , lg__pr_4
    , lg__pr_40
    , lg__pr_48
    , lg__pr_5
    , lg__pr_56
    , lg__pr_6
    , lg__pr_64
    , lg__pr_8
    , lg__pr_px
    , lg__pt_0
    , lg__pt_1
    , lg__pt_10
    , lg__pt_12
    , lg__pt_16
    , lg__pt_2
    , lg__pt_20
    , lg__pt_24
    , lg__pt_3
    , lg__pt_32
    , lg__pt_4
    , lg__pt_40
    , lg__pt_48
    , lg__pt_5
    , lg__pt_56
    , lg__pt_6
    , lg__pt_64
    , lg__pt_8
    , lg__pt_px
    , lg__px_0
    , lg__px_1
    , lg__px_10
    , lg__px_12
    , lg__px_16
    , lg__px_2
    , lg__px_20
    , lg__px_24
    , lg__px_3
    , lg__px_32
    , lg__px_4
    , lg__px_40
    , lg__px_48
    , lg__px_5
    , lg__px_56
    , lg__px_6
    , lg__px_64
    , lg__px_8
    , lg__px_px
    , lg__py_0
    , lg__py_1
    , lg__py_10
    , lg__py_12
    , lg__py_16
    , lg__py_2
    , lg__py_20
    , lg__py_24
    , lg__py_3
    , lg__py_32
    , lg__py_4
    , lg__py_40
    , lg__py_48
    , lg__py_5
    , lg__py_56
    , lg__py_6
    , lg__py_64
    , lg__py_8
    , lg__py_px
    , lg__relative
    , lg__resize
    , lg__resize_none
    , lg__resize_x
    , lg__resize_y
    , lg__right_0
    , lg__right_auto
    , lg__rounded
    , lg__rounded_b
    , lg__rounded_b_full
    , lg__rounded_b_lg
    , lg__rounded_b_md
    , lg__rounded_b_none
    , lg__rounded_b_sm
    , lg__rounded_bl
    , lg__rounded_bl_full
    , lg__rounded_bl_lg
    , lg__rounded_bl_md
    , lg__rounded_bl_none
    , lg__rounded_bl_sm
    , lg__rounded_br
    , lg__rounded_br_full
    , lg__rounded_br_lg
    , lg__rounded_br_md
    , lg__rounded_br_none
    , lg__rounded_br_sm
    , lg__rounded_full
    , lg__rounded_l
    , lg__rounded_l_full
    , lg__rounded_l_lg
    , lg__rounded_l_md
    , lg__rounded_l_none
    , lg__rounded_l_sm
    , lg__rounded_lg
    , lg__rounded_md
    , lg__rounded_none
    , lg__rounded_r
    , lg__rounded_r_full
    , lg__rounded_r_lg
    , lg__rounded_r_md
    , lg__rounded_r_none
    , lg__rounded_r_sm
    , lg__rounded_sm
    , lg__rounded_t
    , lg__rounded_t_full
    , lg__rounded_t_lg
    , lg__rounded_t_md
    , lg__rounded_t_none
    , lg__rounded_t_sm
    , lg__rounded_tl
    , lg__rounded_tl_full
    , lg__rounded_tl_lg
    , lg__rounded_tl_md
    , lg__rounded_tl_none
    , lg__rounded_tl_sm
    , lg__rounded_tr
    , lg__rounded_tr_full
    , lg__rounded_tr_lg
    , lg__rounded_tr_md
    , lg__rounded_tr_none
    , lg__rounded_tr_sm
    , lg__row_auto
    , lg__row_end_1
    , lg__row_end_2
    , lg__row_end_3
    , lg__row_end_4
    , lg__row_end_5
    , lg__row_end_6
    , lg__row_end_7
    , lg__row_end_auto
    , lg__row_gap_0
    , lg__row_gap_1
    , lg__row_gap_10
    , lg__row_gap_12
    , lg__row_gap_16
    , lg__row_gap_2
    , lg__row_gap_20
    , lg__row_gap_24
    , lg__row_gap_3
    , lg__row_gap_32
    , lg__row_gap_4
    , lg__row_gap_40
    , lg__row_gap_48
    , lg__row_gap_5
    , lg__row_gap_56
    , lg__row_gap_6
    , lg__row_gap_64
    , lg__row_gap_8
    , lg__row_gap_px
    , lg__row_span_1
    , lg__row_span_2
    , lg__row_span_3
    , lg__row_span_4
    , lg__row_span_5
    , lg__row_span_6
    , lg__row_start_1
    , lg__row_start_2
    , lg__row_start_3
    , lg__row_start_4
    , lg__row_start_5
    , lg__row_start_6
    , lg__row_start_7
    , lg__row_start_auto
    , lg__scrolling_auto
    , lg__scrolling_touch
    , lg__select_all
    , lg__select_auto
    , lg__select_none
    , lg__select_text
    , lg__self_auto
    , lg__self_center
    , lg__self_end
    , lg__self_start
    , lg__self_stretch
    , lg__shadow
    , lg__shadow_2xl
    , lg__shadow_inner
    , lg__shadow_lg
    , lg__shadow_md
    , lg__shadow_none
    , lg__shadow_outline
    , lg__shadow_sm
    , lg__shadow_xl
    , lg__shadow_xs
    , lg__sr_only
    , lg__static
    , lg__sticky
    , lg__stroke_0
    , lg__stroke_1
    , lg__stroke_2
    , lg__stroke_current
    , lg__subpixel_antialiased
    , lg__table
    , lg__table_auto
    , lg__table_caption
    , lg__table_cell
    , lg__table_column
    , lg__table_column_group
    , lg__table_fixed
    , lg__table_footer_group
    , lg__table_header_group
    , lg__table_row
    , lg__table_row_group
    , lg__text_2xl
    , lg__text_3xl
    , lg__text_4xl
    , lg__text_5xl
    , lg__text_6xl
    , lg__text_base
    , lg__text_black
    , lg__text_blue_100
    , lg__text_blue_200
    , lg__text_blue_300
    , lg__text_blue_400
    , lg__text_blue_500
    , lg__text_blue_600
    , lg__text_blue_700
    , lg__text_blue_800
    , lg__text_blue_900
    , lg__text_center
    , lg__text_current
    , lg__text_gray_100
    , lg__text_gray_200
    , lg__text_gray_300
    , lg__text_gray_400
    , lg__text_gray_500
    , lg__text_gray_600
    , lg__text_gray_700
    , lg__text_gray_800
    , lg__text_gray_900
    , lg__text_green_100
    , lg__text_green_200
    , lg__text_green_300
    , lg__text_green_400
    , lg__text_green_500
    , lg__text_green_600
    , lg__text_green_700
    , lg__text_green_800
    , lg__text_green_900
    , lg__text_indigo_100
    , lg__text_indigo_200
    , lg__text_indigo_300
    , lg__text_indigo_400
    , lg__text_indigo_500
    , lg__text_indigo_600
    , lg__text_indigo_700
    , lg__text_indigo_800
    , lg__text_indigo_900
    , lg__text_justify
    , lg__text_left
    , lg__text_lg
    , lg__text_orange_100
    , lg__text_orange_200
    , lg__text_orange_300
    , lg__text_orange_400
    , lg__text_orange_500
    , lg__text_orange_600
    , lg__text_orange_700
    , lg__text_orange_800
    , lg__text_orange_900
    , lg__text_pink_100
    , lg__text_pink_200
    , lg__text_pink_300
    , lg__text_pink_400
    , lg__text_pink_500
    , lg__text_pink_600
    , lg__text_pink_700
    , lg__text_pink_800
    , lg__text_pink_900
    , lg__text_purple_100
    , lg__text_purple_200
    , lg__text_purple_300
    , lg__text_purple_400
    , lg__text_purple_500
    , lg__text_purple_600
    , lg__text_purple_700
    , lg__text_purple_800
    , lg__text_purple_900
    , lg__text_red_100
    , lg__text_red_200
    , lg__text_red_300
    , lg__text_red_400
    , lg__text_red_500
    , lg__text_red_600
    , lg__text_red_700
    , lg__text_red_800
    , lg__text_red_900
    , lg__text_right
    , lg__text_sm
    , lg__text_teal_100
    , lg__text_teal_200
    , lg__text_teal_300
    , lg__text_teal_400
    , lg__text_teal_500
    , lg__text_teal_600
    , lg__text_teal_700
    , lg__text_teal_800
    , lg__text_teal_900
    , lg__text_transparent
    , lg__text_white
    , lg__text_xl
    , lg__text_xs
    , lg__text_yellow_100
    , lg__text_yellow_200
    , lg__text_yellow_300
    , lg__text_yellow_400
    , lg__text_yellow_500
    , lg__text_yellow_600
    , lg__text_yellow_700
    , lg__text_yellow_800
    , lg__text_yellow_900
    , lg__top_0
    , lg__top_auto
    , lg__tracking_normal
    , lg__tracking_tight
    , lg__tracking_tighter
    , lg__tracking_wide
    , lg__tracking_wider
    , lg__tracking_widest
    , lg__transform_none
    , lg__transition
    , lg__transition_all
    , lg__transition_colors
    , lg__transition_none
    , lg__transition_opacity
    , lg__transition_shadow
    , lg__transition_transform
    , lg__truncate
    , lg__underline
    , lg__uppercase
    , lg__visible
    , lg__w_0
    , lg__w_1
    , lg__w_10
    , lg__w_10over12
    , lg__w_11over12
    , lg__w_12
    , lg__w_16
    , lg__w_1over12
    , lg__w_1over2
    , lg__w_1over3
    , lg__w_1over4
    , lg__w_1over5
    , lg__w_1over6
    , lg__w_2
    , lg__w_20
    , lg__w_24
    , lg__w_2over12
    , lg__w_2over3
    , lg__w_2over4
    , lg__w_2over5
    , lg__w_2over6
    , lg__w_3
    , lg__w_32
    , lg__w_3over12
    , lg__w_3over4
    , lg__w_3over5
    , lg__w_3over6
    , lg__w_4
    , lg__w_40
    , lg__w_48
    , lg__w_4over12
    , lg__w_4over5
    , lg__w_4over6
    , lg__w_5
    , lg__w_56
    , lg__w_5over12
    , lg__w_5over6
    , lg__w_6
    , lg__w_64
    , lg__w_6over12
    , lg__w_7over12
    , lg__w_8
    , lg__w_8over12
    , lg__w_9over12
    , lg__w_auto
    , lg__w_full
    , lg__w_px
    , lg__w_screen
    , lg__whitespace_no_wrap
    , lg__whitespace_normal
    , lg__whitespace_pre
    , lg__whitespace_pre_line
    , lg__whitespace_pre_wrap
    , lg__z_0
    , lg__z_10
    , lg__z_20
    , lg__z_30
    , lg__z_40
    , lg__z_50
    , lg__z_auto
    , m_0
    , m_1
    , m_10
    , m_12
    , m_16
    , m_2
    , m_20
    , m_24
    , m_3
    , m_32
    , m_4
    , m_40
    , m_48
    , m_5
    , m_56
    , m_6
    , m_64
    , m_8
    , m_auto
    , m_px
    , mx_0
    , mx_1
    , mx_10
    , mx_12
    , mx_16
    , mx_2
    , mx_20
    , mx_24
    , mx_3
    , mx_32
    , mx_4
    , mx_40
    , mx_48
    , mx_5
    , mx_56
    , mx_6
    , mx_64
    , mx_8
    , mx_auto
    , mx_px
    , my_0
    , my_1
    , my_10
    , my_12
    , my_16
    , my_2
    , my_20
    , my_24
    , my_3
    , my_32
    , my_4
    , my_40
    , my_48
    , my_5
    , my_56
    , my_6
    , my_64
    , my_8
    , my_auto
    , my_px
    , p_0
    , p_1
    , p_10
    , p_12
    , p_16
    , p_2
    , p_20
    , p_24
    , p_3
    , p_32
    , p_4
    , p_40
    , p_48
    , p_5
    , p_56
    , p_6
    , p_64
    , p_8
    , p_px
    , px_0
    , px_1
    , px_10
    , px_12
    , px_16
    , px_2
    , px_20
    , px_24
    , px_3
    , px_32
    , px_4
    , px_40
    , px_48
    , px_5
    , px_56
    , px_6
    , px_64
    , px_8
    , px_px
    , py_0
    , py_1
    , py_10
    , py_12
    , py_16
    , py_2
    , py_20
    , py_24
    , py_3
    , py_32
    , py_4
    , py_40
    , py_48
    , py_5
    , py_56
    , py_6
    , py_64
    , py_8
    , py_px
    , shadow
    , shadow_2xl
    , shadow_inner
    , shadow_lg
    , shadow_md
    , shadow_none
    , shadow_outline
    , shadow_sm
    , shadow_xl
    , shadow_xs
    )

import Css
import Css.Media


m_0 : Css.Style
m_0 =
    Css.batch
        [ Css.margin (Css.px 0)
        ]
